openapi: 3.0.0
info:
  description: Back-End (RESTful API) Web Application Alta Store
  version: "1.0.0"
  title: BE Web Application Alta Store

tags:
  - name: Product Category
    description: Resource for insert, modifiying and getting Product Categories
  - name: Product
    description: Resource for insert, modifiying and getting Products
  - name: Purchase Receiving
    description: Resource for insert, modifiying and getting Purchase Receivings

paths:
  /v1/categories:
    post:
      tags:
        - Product Category
      summary: Insert New Product Category
      operationId: AddNewProductCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCategory"
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        409:
          description: Data Already Exists
      security:
        - bearerAuth: []
    get:
      tags:
        - Product Category
      summary: Get List of Product Category
      operationId: GetListofProductCategory
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductCategoryViewAll"
  
  /v1/categories/{id}:
    get:
      tags:
        - Product Category
      summary: Get Product Category By ID
      operationId: GetProductCategory
      parameters:
        - in: path
          name: id
          description: Id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: ec9052e4-58c5-446b-b948-982e41f17b70
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductCategoryView"
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    
    put:
      tags:
        - Product Category
      summary: Update Product Category
      operationId: UpdateProductCategory
      parameters:
        - in: path
          name: id
          description: Id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: ec9052e4-58c5-446b-b948-982e41f17b70
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCategory"

      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    
    delete:
      tags:
        - Product Category
      summary: Delete Product Category
      operationId: DeleteProductCategory
      parameters:
        - in: path
          name: id
          description: Id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: ec9052e4-58c5-446b-b948-982e41f17b70
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
  
  /v1/products:
    post:
      tags:
        - Product
      summary: Insert New Product
      operationId: InsertNewProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDetail"
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Bad Request
    
    get:
      tags:
        - Product
      summary: Get Product By Parameters
      operationId: Get Product By parameters
      parameters:
        - in: query
          name: code
          description: code to be passed as a query
          required: false
          schema:
            type: string
            example: MIE0000010000002
        - in: query
          name: name
          description: name to be passed as a query
          required: false
          schema:
            type: string
            example: MIE SEDAP RASA AYAM BAWANG
        - in: query
          name: isactive
          description: isactive (true/false) to be passed as a query
          required: false
          schema:
            type: boolean
            example: true
        - in: query
          name: categoryname
          description: categoryname to be passed as a query
          required: false
          schema:
            type: string
            example: MINUMAN DINGIN
      
      security:
        - bearerAuth: []
      
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductViewAll"
  
  /v1/products/{id}:
    get:
      tags:
        - Product
      summary: Get Product By ID
      operationId: GetProductById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 550f0744-60ef-48f2-97cf-fed29b571cc9
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductView"
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    
    put:
      tags:
        - Product
      summary: Modify Product
      operationId: ModifyProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDetail"
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    
    delete:
      tags:
        - Product
      summary: Delete Product
      operationId: DeleteProduct
      parameters:
        - in: path
          name: id
          description: Id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: 550f0744-60ef-48f2-97cf-fed29b571cc9
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
  
  /v1/purchases:
    post:
      tags:
        - Purchase Receiving
      summary: Insert New Purchase Receiving
      operationId: InsertNewPurchaseReceiving
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseReceivingInsertDto"
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Data Already Exists
    get:
      tags:
        - Purchase Receiving
      summary: Get Purchase Receiving By parameters
      operationId: GetPurchaseReceivingByparameters
      parameters:
        - in: query
          name: code
          description: code to be passed as a query
          required: false
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseSummary"
  
  /v1/purchases/{id}:
    get:
      tags:
        - Purchase Receiving
      summary: Get Purchase Receiving By Id
      operationId: GetPurchaseReceivingById
      parameters:
        - in: path
          name: id
          description: id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: 6f409145-e801-4198-abbe-c03c20d9fe27
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseReceivingView"
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    put:
      tags:
        - Purchase Receiving
      summary: Update Items In Purchase Receiving
      operationId: UpdatePurchaseReceiving
      parameters:
        - in: path
          name: id
          description: id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: cde144e2-eecc-4f1b-bb99-5b0ecf662a8f
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: PCH0003
                description:
                  type: string
                  example: "BARANG PROMO MINGGU INI"
                details:
                  type: array
                  items:
                    type: object
                    properties:
                      productid:
                        type: string
                        format: uuid
                      price:
                        type: number
                        example: 3000
                      qty:
                        type: number
                        example: 10
                      status:
                        type: number
                        example: 1
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found
    
    delete:
      tags:
        - Purchase Receiving
      summary: Delete Purchase Receiving By Id
      operationId: DeletePurchaseReceivingById
      parameters:
        - in: path
          name: id
          description: id to be passed as a path
          required: true
          schema:
            type: string
            format: uuid
            example: 6f409145-e801-4198-abbe-c03c20d9fe27
      responses:
        200:
          description: Success
        400:
          description: Bad Input Parameter
        404:
          description: Data Not Found

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    ProductCategory:
      type: object
      properties:
        code:
          type: string
          example: MIE000001
        name:
          type: string
          example: MIE INSTAN
    
    ProductCategoryViewAll:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
            example: ec9052e4-58c5-446b-b948-982e41f17b70
          code:
            type: string
            example: MIE000001
          name:
            type: string
            example: MINUMAN DINGIN
          updated_at:
            type: string
            format: date-time
            example: "2021-10-31T08:13:57.528637Z"

    ProductCategoryView:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: ec9052e4-58c5-446b-b948-982e41f17b70
        code:
          type: string
          example: MIE000001
        name:
          type: string
          example: MINUMAN DINGIN
        updated_at:
          type: string
          format: date-time
          example: "2021-10-31T08:13:57.528637Z"

    ProductDetail:
      type: object
      properties:
        code:
          type: string
          example: MIE0000010000002
        name:
          type: string
          example: MIE SEDAP RASA AYAM BAWANG
        price:
          type: number
          example: 3000
        isactive:
          type: boolean
          example: true
        productcategoryid:
          type: string
          format: uuid
          example: 05162084-0b62-4b79-bbe3-baedb5f21717
        unitname:
          type: string
          example: pak
        description:
          type: string
          example: Mie instan menyehatkan
    
    ProductViewAll:
      type: array
      items:
        $ref: "#/components/schemas/ProductView"
    
    ProductView:
        type: object
        properties:
          id:
            type: string
            format: uuid
            example: 550f0744-60ef-48f2-97cf-fed29b571cc9
          code:
            type: string
            example: '00000000000001'
          name:
            type: string
            example: MINUMAN CAP GAJAH IJO
          price:
            type: number
            example: 3000
          qty:
            type: number
            example: 10
          qtycart:
            type: number
            example: 2
          isactive:
            type: boolean
            example: true
          productcategoryname:
            type: string
            example: MINUMAN DINGIN
          unitname:
            type: string
            example: pak
          description:
            type: string
            example: Minuman dingin menyegarkan

    PurchaseReceivingInsertDto:
      type: object
      properties:
        code:
          type: string
          example: NOTA0001
        datereceived:
          type: string
          format: date-time
          example: "2018-09-22T12:42:31Z"
        receivedby:
          type: string
          example: Bambang
        description:
          type: string
          example: NOTA PEMBELIAN UNTUK PROMO
        details:
          type: array
          items:
            type: object
            properties:
              ProductId:
                type: string
                format: uuid
                example: a523804c-5266-4d89-b4f7-ac4649081493
              qty:
                type: number
                example: 10
              Price:
                type: number
                example: 3000
              
    PurchaseReceivingUpdateDto:
      type: object
      properties:
        invoicedate:
          type: string
          format: date
        receivedby:
          type: string
          example: Bambang
        description:
          type: string
          example: Pembelian Berhasil
        details:
          type: array
          items:
            type: object
            properties:
              ProductId:
                type: string
                format: uuid
              Price:
                type: number
                example: 1000000
              qty:
                type: number
                example: 50
    
    PurchaseSummary:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
            example: 6f409145-e801-4198-abbe-c03c20d9fe27
          code:
            type: string
            example: NOTA0001
          datereceived:
            type: string
            format: date-time
            example: "2018-09-22T12:42:31Z"
          receivedby:
            type: string
            example: "WIDYAADEBAGUS"
          description:
            type: string
            example: "NOTA PEMBELIAN UNTUK PROMO"
    
    PurchaseReceivingView:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
            example: 6f409145-e801-4198-abbe-c03c20d9fe27
          code:
            type: string
            example: NOTA0001
          datereceived:
            type: string
            format: date-time
          receivedby:
            type: string
            example: WIDYAADEBAGUS
          description:
            type: string
            example: NOTA PEMBELIAN UNTUK PROMO
          details:
            type: array
            items:
              type: object
              properties:
                productid:
                  type: string
                  format: uuid
                  example: a523804c-5266-4d89-b4f7-ac4649081493
                productcode:
                  type: string
                  example: "00000000000002"
                productname:
                  type: string
                  example: MINUMAN CAP GAJAH IJO
                price:
                  type: number
                  example: 3000
                qty:
                  type: number
                  example: 50