// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	purchasereceiving "AltaStore/business/purchasereceiving"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RepositoryDetail is an autogenerated mock type for the RepositoryDetail type
type RepositoryDetail struct {
	mock.Mock
}

// DeletePurchaseReceivingDetail provides a mock function with given fields: purchaseId, productId, remover, deleter
func (_m *RepositoryDetail) DeletePurchaseReceivingDetail(purchaseId *string, productId *string, remover *string, deleter time.Time) error {
	ret := _m.Called(purchaseId, productId, remover, deleter)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string, *string, *string, time.Time) error); ok {
		r0 = rf(purchaseId, productId, remover, deleter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurchaseReceivingDetail2 provides a mock function with given fields: id, deleter
func (_m *RepositoryDetail) DeletePurchaseReceivingDetail2(id string, deleter string) error {
	ret := _m.Called(id, deleter)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, deleter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPurchaseReceivingDetailById provides a mock function with given fields: id
func (_m *RepositoryDetail) GetPurchaseReceivingDetailById(id string) (*purchasereceiving.PurchaseReceivingDetail, error) {
	ret := _m.Called(id)

	var r0 *purchasereceiving.PurchaseReceivingDetail
	if rf, ok := ret.Get(0).(func(string) *purchasereceiving.PurchaseReceivingDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*purchasereceiving.PurchaseReceivingDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPurchaseReceivingDetailByPurchaseReceivingId provides a mock function with given fields: id
func (_m *RepositoryDetail) GetPurchaseReceivingDetailByPurchaseReceivingId(id string) (*[]purchasereceiving.PurchaseReceivingDetail, error) {
	ret := _m.Called(id)

	var r0 *[]purchasereceiving.PurchaseReceivingDetail
	if rf, ok := ret.Get(0).(func(string) *[]purchasereceiving.PurchaseReceivingDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]purchasereceiving.PurchaseReceivingDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPurchaseReceivingDetail provides a mock function with given fields: item
func (_m *RepositoryDetail) InsertPurchaseReceivingDetail(item *purchasereceiving.PurchaseReceivingDetail) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*purchasereceiving.PurchaseReceivingDetail) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePurchaseReceivingDetail provides a mock function with given fields: purchaseId, productId, price, qty, modifier, updater
func (_m *RepositoryDetail) UpdatePurchaseReceivingDetail(purchaseId *string, productId *string, price *int, qty *int, modifier *string, updater time.Time) error {
	ret := _m.Called(purchaseId, productId, price, qty, modifier, updater)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string, *string, *int, *int, *string, time.Time) error); ok {
		r0 = rf(purchaseId, productId, price, qty, modifier, updater)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
